CREATE TABLE users (
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name VARCHAR(25) NOT NULL,
	password VARCHAR(65),
	CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE documents (
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	category VARCHAR(25) NOT NULL,
	description VARCHAR(1000),
	due_date DATE,
	CONSTRAINT documents_pk PRIMARY KEY (id)
);